#!/bin/bash

SCRIPT_PATH="${BASH_SOURCE[0]%/*}"                                        # /.svm/shims
SVM_PATH=${SCRIPT_PATH%/shims}                                            # /.svm/
VERSIONS_PATH="$SVM_PATH/versions"                                        # /.svm/versions
VERSION_FILE_PATH="$SVM_PATH/version"                                     # /.svm/version

#
# helper functions
#

_svm_error_message() {
  local message="$1"
  echo -e "\033[41m $message \033[0m"
}

_svm_trim_string() {
  local string="$1"
  string="${string##*( )}" # trim leading whitespace
  string="${string%%*( )}" # trim trailing whitespace
  echo $string
}

_svm_get_active_version() {
  local activeVersion=""

  if [ -f "$VERSION_FILE_PATH" ]; then
    activeVersion=`cat $VERSION_FILE_PATH`
    activeVersion=$(_svm_trim_string "$activeVersion")
  fi

  echo $activeVersion
}

_svm_get_scriptcs_executable() {
  local version="$1"
  local scriptcs="$VERSIONS_PATH/$version/scriptcs.exe"
  echo $scriptcs
}

#
# shim
#

version=$(_svm_get_active_version)
if [ "$version" == "" ]; then
  _svm_error_message "No active scriptcs found. Use 'svm use <version>' to set the active scriptcs version."
  exit
fi
scriptcs=$(_svm_get_scriptcs_executable "$version")
if [ ! -f "$scriptcs" ]; then
  _svm_error_message "The active scriptcs could not be found at '$scriptcs'. Use 'svm use <version>' to correctly set the active scriptcs version."
  exit
fi
mono "$scriptcs" "$@"
